### ISSUE TITLE
Conservative Temperature not in params table?

### ISSUE THREAD

**Issue by sdiggs** [cchdo/params#3]
Attempting a translation of WHP-Exchange formatted 'reported' CTD profiles to CCHDO's netCDF-CF using 'cchdo.hydro' (ref: GO_SHIP Easy).  Source file included.

[sr04_1989_0036_ct1_csv.txt](https://github.com/cchdo/params/files/6137895/sr04_1989_0036_ct1_csv.txt)

**References:**

1. http://www.teos-10.org/pubs/old_TEOS-10_manuals/TEOS-10_Manual_13th_April_2010.pdf
2. http://clipc-services.ceda.ac.uk/dreq/u/sea_water_added_conservative_temperature.html
3. http://vocab.nerc.ac.uk/standard_name/sea_water_added_conservative_temperature/

---
COMMAND: _**python -m cchdo.hydro sr04_1989_0036_ct1.csv  sr04_1989_0036_ctd.nc**_

[23:26:41] INFO     cli: Loading read_exchange                                                                                                                                                                    __main__.py:18           INFO     read_exchange: Loading object from local file path                                                                                                                                                 io.py:280           INFO     read_exchange: Found filetype: CTD                                                                                                                                                                 io.py:328Traceback (most recent call last):  File "/home/sdiggs/.pyenv/versions/3.8.5/lib/python3.8/site-packages/cchdo/hydro/exchange/io.py", line 125, in _bottle_get_params    params[WHPNames[(param, unit)]] = index  File "/home/sdiggs/.pyenv/versions/3.8.5/lib/python3.8/site-packages/cchdo/params/__init__.py", line 239, in __getitem__    return self._cached_dict[key]

**KeyError: ('CTDCT', 'ITS-90')**

The above exception was the direct cause of the following exception:
Traceback (most recent call last):  File "/home/sdiggs/.pyenv/versions/3.8.5/lib/python3.8/runpy.py", line 194, in _run_module_as_main    return _run_code(code, main_globals, None,  File "/home/sdiggs/.pyenv/versions/3.8.5/lib/python3.8/runpy.py", line 87, in _run_code    exec(code, run_globals)  File "/home/sdiggs/.pyenv/versions/3.8.5/lib/python3.8/site-packages/cchdo/hydro/__main__.py", line 29, in <module>    cli()  File "/home/sdiggs/.pyenv/versions/3.8.5/lib/python3.8/site-packages/click/core.py", line 829, in __call__    return self.main(*args, **kwargs)  File "/home/sdiggs/.pyenv/versions/3.8.5/lib/python3.8/site-packages/click/core.py", line 782, in main    rv = self.invoke(ctx)  File "/home/sdiggs/.pyenv/versions/3.8.5/lib/python3.8/site-packages/click/core.py", line 1066, in invoke    return ctx.invoke(self.callback, **ctx.params)  File "/home/sdiggs/.pyenv/versions/3.8.5/lib/python3.8/site-packages/click/core.py", line 610, in invoke    return callback(*args, **kwargs)  File "/home/sdiggs/.pyenv/versions/3.8.5/lib/python3.8/site-packages/cchdo/hydro/__main__.py", line 21, in cli    ex = read_exchange(exchange_path)  File "/home/sdiggs/.pyenv/versions/3.8.5/lib/python3.8/site-packages/cchdo/hydro/exchange/io.py", line 388, in read_exchange    whp_params = _bottle_get_params(zip(params, units))  File "/home/sdiggs/.pyenv/versions/3.8.5/lib/python3.8/site-packages/cchdo/hydro/exchange/io.py", line 127, in _bottle_get_params    raise 

**ExchangeParameterUndefError(cchdo.hydro.exchange.exceptions.ExchangeParameterUndefError: missing parameter def ('CTDCT', 'ITS-90')**

**Comment by DocOtak** [comment]
This was fixed in c577f7ccbcdda1b2a3091b13c947176d98572003
